name: LeetCode Metrics

on:
  workflow_dispatch:

  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.leetcode.svg

          token: ${{ secrets.GITHUB_TOKEN }}

          user: shailjajha0410

          base: ""

          plugin_leetcode: yes
          plugin_leetcode_user: ShailjaJha
          plugin_leetcode_sections: solved

          output_action: commit
